version: "3"
services:
  mongo:
    container_name: mongo-mern-docker-boilerplate
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    networks:
      - default
    volumes:
      - ./db/db-init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./db/mongo-volume:/data/db
    environment:
      - MONGO_INITDB_DATABASE=mern_docker_starter
      - MONGO_INITDB_USER=local_user
      - MONGO_INITDB_PASSWORD=Password123

  backend:
    container_name: node-mern-docker-boilerplate
    build:
      context: ./backend
      dockerfile: deploy/production/Dockerfile
    networks:
      - default
      - frontend
    volumes:
      - ./backend:/home/node/app
    environment:
      - NODE_ENV=production
    env_file:
      - ./backend/.env.production
    tty: true
    stdin_open: true
    depends_on:
      - mongo
    ports:
      - "5000:4000"

  frontend:
    container_name: react-mern-docker-boilerplate
    build:
      context: ./frontend
      dockerfile: deploy/production/Dockerfile
    networks:
      - frontend
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
    tty: true
    stdin_open: true
    ports:
      - "3000:80"

  nginx:
    image: nginx:latest
    container_name: my-mern-nginx
    ports:
      - "80:80" # Map container port to host port
    volumes:
      - ./frontend/build:/usr/share/nginx/html    # Mount the React production build
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf    # Mount Nginx configuration
    depends_on:
      - frontend

networks:
  default:
    name: backend-network-mern-docker-boilerplate
  frontend:
    name: frontend-network-mern-docker-boilerplate
