version: "3"
services:
  mongo:
    container_name: docker-mern-db-prod
    build:
      context: ./db
      dockerfile: deploy/production/Dockerfile
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    restart: always
    networks:
      - mern-network  

  backend:
    container_name: docker-mern-backend-prod
    build:
      context: ./backend
      dockerfile: deploy/production/Dockerfile
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    networks:
      - mern-network

  nginx:
    container_name: docker-mern-nginx-prod
    build:
      context: ./
      dockerfile: ./nginx/deploy/production/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - mern-network
    restart: always

volumes:
  mongo_data:

networks:
  mern-network:  
    driver: bridge
